### ISSUE TITLE
HCC 'roctracer-hip-frontend180823' build error

### ISSUE THREAD

**Issue by parallelo** [ROCm/roctracer#1]
Hi, I'm hitting some errors when following the instructions posted in the README.  

When building HCC like so:  
```
git clone --recursive -b roctracer-hip-frontend-180823 https://github.com/eshcherb/hcc.git
cd hcc/
mkdir build && cd build && cmake -DUSE_PROF_API=1 .. && make -j$(nproc)
```

I see this error:  
```
...
[100%] Linking CXX static library ../lib/libamptest.a
[100%] Built target amptest
In file included from /root/hcc/lib/hsa/mcwamp_hsa.cpp:51:
/root/hcc/lib/hsa/activity_prof.h:149:10: fatal error: 'prof_protocol.h' file
      not found
#include "prof_protocol.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
```

Looks like just a test is failing to build, but wanted to get your take first.  Perhaps I should be using a different branch of HCC?

**Comment by eshcherb** [comment]
There is cmake option -DPROF_API_HEADER_PATH=<your path>/roctracer/inc/ext which sets path to the tracer protocol header.
By default it looks in /opt/rocm/roctracer/include/ext
