### ISSUE TITLE
[Issue]: Roctracer returns correlation_id of 0 for all communication kernels

### ISSUE THREAD

**Issue by sraikund16** [ROCm/roctracer#100]
### Problem Description

When profiling, we observe that the activity_record_t/roctracer_record_t objects for communication kernels all have a correlation_id of 0. For example, we see CPU event `hipExtLaunchKernel` with correlation 29170; however, its corresponding GPU kernel, `ncclDevKernel_Generic(ncclDevComm*, channelMasks, ncclWork*)`, has correlation of 0. We see that for non-CCL events, the correlation_id of the CPU and GPU events do match despite using the same method of getting correlation_id as CCL events. 

We obtain the correlation_ids for all async roctracer activities in kineto within this callback: https://github.com/pytorch/kineto/blob/main/libkineto/src/RoctracerLogger.cpp#L295

Thanks in advance!

### Operating System

CentOS Stream 9

### CPU

AMD EPYC 7713

### GPU

AMD Instinct MI300X

### ROCm Version

6.1.0.60100-82

### ROCm Component

roctracer

**Comment by jithunnair-amd** [comment]
cc @mwootton

**Comment by sraikund16** [comment]
@mwootton I added a debug in this PR: https://github.com/pytorch/kineto/pull/982?fbclid=IwZXh0bgNhZW0CMTEAAR3_RK7vE-FsNn3Jf25uGjHaqN9H5vubjl7vdLwfCrUZkylydG7hDC2fB6o_aem_uPIqohTBkAW8PZwOnSB96Q

And saw the following prints:
`WARNING:2024-08-28 15:29:41 3273561:3284767 RoctracerLogger.cpp:307] Correlation id is 0 for record: ncclDevKernel_Generic(ncclDevComm*, channelMasks, ncclWork*)`

It seems like the callback is populating the id with 0 before we even process it

**Comment by mwootton** [comment]
I was able to find an internal issue where this was addressed.  It is fixed in rocm6.2.

**Comment by sraikund16** [comment]
Confirmed this was fixed in 6.2.0
