### ISSUE TITLE
[Issue]: Roctracer Communication Kernel Names are too Generic

### ISSUE THREAD

**Issue by sraikund16** [ROCm/roctracer#101]
### Problem Description

For GPU traces, all the communication kernels are named like the following: `ncclDevKernel_Generic(ncclDevComm*, channelMasks, ncclWork*)`, which is not very descriptive. Because of this, it is hard to know whether it is an allgather, or an allreuce, or a sendrecv, or other type of communication collectives. It would be most ideal if the `kernel_name` field in `activity_record_t` could have the specific kernel type, but an alternative could be to use `activity_kind_t kind` or `activity_op_t op`.

Thanks in advance!

### Operating System

CentOS Stream 9

### CPU

AMD EPYC 7713

### GPU

AMD Instinct MI300X

### ROCm Version

ROCm 6.0.1

### ROCm Component

roctracer

**Comment by jithunnair-amd** [comment]
cc @mwootton

**Comment by jithunnair-amd** [comment]
@sraikund16 Afaict, this is an ask for the rccl team ,if that. Roctracer is just reporting what info rccl provides it. @ammarwa to confirm

**Comment by jithunnair-amd** [comment]
@sraikund16 Also, does this issue not exist when using nccl? Do you get the collective type info you're looking for when you use nccl?

**Comment by sraikund16** [comment]
@jithunnair-amd For nccl traces, the naming is more specific for example:
ncclKernel_ReduceScatter_RING_LL_Sum___nv_bfloat16(ncclDevComm*, unsigned long, ncclWork*)

**Comment by mwootton** [comment]
It depends on which nccl kernels are being invoked.   I see examples of both these in rocm traces:

- ncclKernel_SendRecv_RING_SIMPLE_Sum_int8_t(ncclDevComm*, unsigned long, ncclWork*)
- ncclDevKernel_Generic(ncclDevComm*, channelMasks, ncclWork*)

It is like for like.  Even if it weren't, roctracer is supposed to report the name of the kernel that was executed not make up a name of it's own.  Roctracer has absolutely no information to use to embellish the name.  Pytorch on the other hand could, e.g. push an autograd range with the collective type/size and an external correlation id.  Then you would have some reliable context for the kernel execution.

**Comment by sraikund16** [comment]
Not needed now that we have correlation IDs for comms
