### ISSUE TITLE
[Feature]: Add Roctracer Timestamp Callback Call

### ISSUE THREAD

**Issue by sraikund16** [ROCm/roctracer#102]
### Suggestion Description

When looking at the Timestamp Operations in roctracer.h, I noticed there is no way to change the clock that roctracer uses to set timestamps. This forces the user to use a system clock, which is not guaranteed to be monotonic. It would be useful to have a rocm version of cuptiActivityRegisterTimestampCallback so that we can set the timestamps to be monotonic. 

Thank you.

### Operating System

CentOS Stream 9

### GPU

N/A

### ROCm Component

roctracer

**Comment by pruthvistony** [comment]
@mwootton

**Comment by jrmadsen** [comment]
There are inherent underlying problems here which block this for being easily implemented. Roctracer/rocprofiler-sdk do not have control over the clock for GPU timestamps and those timestamps are given to us asynchronously. Thus, your callback cannot be invoked when the timestamp is recorded. It may be possible but it will likely require changes in the driver. 

Side note, internally within the profiling tool libraries, we use [CLOCK_BOOTTIME](https://www.man7.org/linux/man-pages/man3/clock_settime.3.html) which _is_ monotonic and _generally_ aligns with the GPU timestamps (occasionally, we’ve detected skews which requires small shifts)

**Comment by darren-amd** [comment]
Hi @sraikund16,

Please see the comments above, thanks!
