### ISSUE TITLE
[Issue]: build fails due to missing package but it is falsely reporting error because it is installed

### ISSUE THREAD

**Issue by jdgh000** [ROCm/roctracer#108]
### Problem Description

-- The C compiler identification is GNU 11.5.0
-- The CXX compiler identification is GNU 11.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found Python3: /bin/python3.12 (found version "3.12.6") found components: Interpreter
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'CppHeaderParser'
CMake Error at src/CMakeLists.txt:41 (message):
  The "CppHeaderParser" Python3 package is not installed.  Please install it
  using the following command: "pip3 install CppHeaderParser".

-- Configuring incomplete, errors occurred!
pip3 list | grep cpp -i
CppHeaderParser          2.7.4

rocm523, rhel9

### Operating System

rhel9

### CPU

epyc

### GPU

mi210

### ROCm Version

ROCm 6.2.3

**Comment by tcgu-amd** [comment]
Hi @jdgh000, can you show the outputs of 
```
which python3
which pip3
```
Thanks!

**Comment by jdgh000** [comment]
here are some of my findings in:
https://github.com/ROCm/clr/issues/107

**Comment by tcgu-amd** [comment]
Hi @jdgh000 thanks for the update. Do you consider this issue resolved then?

**Comment by jdgh000** [comment]
it is not! there is a bin/python3.12 is created in build folder, i dont know how it is being created and can not change that.

**Comment by tcgu-amd** [comment]
@jdgh000 Okay, have you checked to see if CppHeaderParser is in `/bin/python3.12 -m pip list`? Would you be able to

```
1. Delete build folder & recreate it
2. run `/bin/python3.12 -m pip install CppHeaderParser`
3. Build again
```

Thanks!

**Comment by jdgh000** [comment]
i did it already yesterday, but it created same 3.12 link. I just could not figure out where and how this is being created otherwise so I can try hack to change to 3.9 (pointed by python3)

**Comment by jdgh000** [comment]
it says no pip. I would not go this route again because as mentioned, using 3.12 1) breaks all other pip packages as unavailable 2) even if it works, it is just hacky and temp solution. 
sudo /bin/python3.12 -m pip install CppHeaderParser
/bin/python3.12: No module named pip
I would rather continue using what is pointed by 3.9.

**Comment by tcgu-amd** [comment]
@jdgh000 Sorry that didn't work. `cmake` acts weird if you have multiple versions of Python installed; it will just choose a random one. The simple solution is uninstall all other versions except Python3.9. If that do not work, try replacing line 34 of src/CMakeLists.txt with (modify the path with the path to Python 3.9 interpreter.
```
set(Python3_ROOT_DIR "/path/topython3.9")
find_package(Python3 REQUIRED COMPONENTS Interpreter)
``
Let know if this works. Thanks!

**Comment by jrmadsen** [comment]
Do not edit the CMake, just pass `-DPython3_ROOT_DIR=…` via the command line or explicitly pass `-DPython3_EXECUTABLE=…`. The search procedure is not random. Use environment variables like `CMAKE_PREFIX_PATH` to help guide to where to find things.

**Comment by tcgu-amd** [comment]
Hi @jrmadsen thanks for the guidance! @jdgh000 Please follow @jrmadsen's approach which is better.

**Comment by jdgh000** [comment]
ok that sounds reasonable, will try out.

**Comment by jdgh000** [comment]
-DPython3_EXECUTABLE= appears to work
