### ISSUE TITLE
Difficulty of using roctracer in pure C program

### ISSUE THREAD

**Issue by mxz297** [ROCm/roctracer#20]
My name is Xiaozhu Meng and I am from the HPCTookit project of Rice University. We are integrating roctracer into the HPCToolkit's measurement infrastructure for performance analysis on AMD GPUs. 

The `hpcrun` utility in HPCToolkit is written in pure C. We are having several difficulties of integrating roctracer into `hpcrun` due to C++ usage in roctracer header files. We have made some small changes to roctracer code to get rid of default parameters and add `typedef` for `struct` declarations. We will create PRs when our changes are stable. We have encountered several non-trivial conversions in roctracer from C++ to C:

1. `inc/cb_table.h` uses `<mutex>`, namespace, and defines a class. 

2. `inc/roctracer_hcc.h` includes `hc_prof_runtime.h`, which contains C++ code. 

3. `inc/roctracer_kfd.h` and `inc/roctracer_hsa.h` use templates. 

4. `inc/ext/hsa_rt_utils.hpp` uses classes

In addition to the header files, the implementation of roctracer also contains C++ code. Note that the users of HPCToolkit may compiled their applications with one version of C++ compiler and compiled HPCTookit and roctracer with another version of compiler. While I think it is possible to properly rpath the C++ dependencies so that roctracer would pick up the correct the correct C++ dependencies, but I am not sure. 

How should we plan together to make roctracer useable from a C program and portable across different C++ compilers? I appreciate any comments and feedback.

Thanks!

**Comment by eshcherb** [comment]
I have addressed the items 2 and 3.
The items 1 and 4 are not part of external C API. 'hsa_rt_utils.hpp' is a C++ wrapper over HSA timestamp API.
