### ISSUE TITLE
rocm 3.0 cannot find the inc/kfd_ostream_ops.h

### ISSUE THREAD

**Issue by ginsongsong** [ROCm/roctracer#34]
Hi all,

Currently, I want to update roctracer from 2.0 to 3.0. but I ran  build.sh will get the bellow messages.

`
In file included from /opt/rocm/roctracer/src/core/roctracer.cpp:30:0:
/opt/rocm/roctracer/inc/roctracer_kfd.h:30:10: fatal error: inc/kfd_ostream_ops.h: No such file or directory
 #include "inc/kfd_ostream_ops.h"
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
`

**Comment by eshcherb** [comment]
You need the following python modules according to the roctracer README https://github.com/ROCm-Developer-Tools/roctracer#to-build-and-run-test

  The required modules: CppHeaderParser, argparse.
  To install:
  sudo pip install CppHeaderParser argparse
