### ISSUE TITLE
aomp build fails with python3

### ISSUE THREAD

**Issue by powderluv** [ROCm/roctracer#48]
Looks like top of master aomp (13.x) fails with python3 since it tries to build rocm-4.0.x branch and the python3 fixes are in amd-master. 

Would it be possible to merge amd-master into the rocm-4.0.x branch or update aomp to point to the right AOMP_TRACE_REPO_BRANCH in 
https://github.com/ROCm-Developer-Tools/aomp/blob/ede3f2ab68997cfd788e34d8362ba28092902658/bin/aomp_common_vars#L243

**Comment by ppanchad-amd** [comment]
@powderluv Is this ticket still relevant? Thanks!

**Comment by ppanchad-amd** [comment]
@powderluv Closing ticket. Please re-open the ticket if you still see the issue with the latest ROCm. Thanks!
