### ISSUE TITLE
roctracer_op_string returns  "Unknown command type"

### ISSUE THREAD

**Issue by reza-amd** [ROCm/roctracer#49]
roctracer_op_string  returns "Unknown command type" for (domain=2, op=1, kind=4606).
We have received these "domain", "op", and "kind" from an activity record callback.
 @deven-amd, @sunway513

**Comment by ppanchad-amd** [comment]
@reza-amd Is this ticket still relevant? If not, please close the ticket. Thanks!

**Comment by jamesxu2** [comment]
Closing due to lack of response. Feel free to reopen this issue if you circle back @reza-amd .
