### ISSUE TITLE
"roctracer_enable_op_activity" symbol does not exist in the library to link

### ISSUE THREAD

**Issue by reza-amd** [ROCm/roctracer#50]
"roctracer_enable_op_activity" does not exist for linking. We use "roctracer_enable_op_activity_expl" instead. In the roctracer documentations it shows that "roctracer_enable_op_activity" should be available.

**Comment by ppanchad-amd** [comment]
@reza-amd Can you please check if this issue still exists with the latest ROCm 6.2? If not, please close the ticket. Thanks!

**Comment by darren-amd** [comment]
Hi @reza-amd,

I tried building a test file that contains the symbol `roctracer_enable_op_activity` available here: [MatrixTranspose_test](https://github.com/ROCm/roctracer/blob/fee1f00ddcbd6149cb246569a69a14d9a1575ff0/test/app/MatrixTranspose_test.cpp#L371), and was able to build and run it successfully using the instructions here: [README](https://github.com/ROCm/roctracer/blob/amd-master/README.md).

Looking into the library libroctracer64 using the command `nm -D /path/to/libroctracer64.so | grep roctracer_enable_op_activity`, roctracer_enable_op_activity is defined in the library:
```
/opt/rocm-6.2.0/lib$ nm libroctracer64.so.4.1.60200 -D | grep enable_op_activity
0000000000024590 T roctracer_enable_op_activity@@ROCTRACER_4.1
0000000000024540 T roctracer_enable_op_activity_expl@@ROCTRACER_4.0 
```

Please try updating to the latest version of ROCm (6.2) and building your code again and let me know if the error persists. Thanks!
