### ISSUE TITLE
Sample provided in the doc folder is not compatible with ROCm4.1 APIs.

### ISSUE THREAD

**Issue by reza-amd** [ROCm/roctracer#52]

**Comment by darren-amd** [comment]
Hi @reza-amd,

I was able to run a few sample code examples on the lates version of ROCm. Could you please update ROCm to the latest version (6.2), and try running the sample again?

Could you also provide the sample? It may no longer be compatible with the APIs of the latest version. Thanks!

**Comment by darren-amd** [comment]
Hi @reza-amd,

Closing this ticket for inactivity. Please open another ticket if the issue persists, thanks!
