### ISSUE TITLE
Memory Pool destructor uses allocator_default.

### ISSUE THREAD

**Issue by louisespellacy-arm** [ROCm/roctracer#54]
In `MemoryPool.h`, the destructor uses `allocator_default` even if a allocator function has been provided via `roctracer_properties_t` and was used in the constructor. 

https://github.com/ROCm-Developer-Tools/roctracer/blob/0876c253d8b6380a1d6bd1f2b34c5b4c1e8c94db/src/core/memory_pool.h#L91-L98

If custom memory management is carried out in `properties.alloc_func`, then the required custom free-ing of the memory cannot be matched when the allocator default is used in the destructor. This creates a double-free or other possible problems.

**Comment by bertwesarg** [comment]
@TimourPaltashev any progress here?

**Comment by TimourPaltashev** [comment]
Hi Kiumars,
Do we have any activity on this issue??
https://github.com/ROCm-Developer-Tools/roctracer/issues/54

Many thanks,
TT.

**Comment by TimourPaltashev** [comment]
[AMD Official Use Only - General]

Hi Timour,

I think this code has changed for rocm-5.3, let me double check and send you update

Best regards,
Kiumars

From: Paltashev, Timour ***@***.***>
Sent: Tuesday, June 14, 2022 12:32 PM
To: ROCm-Developer-Tools/roctracer ***@***.***>; ROCm-Developer-Tools/roctracer ***@***.***>
Cc: Sabeti, Kiumars ***@***.***>; Bert Wesarg ***@***.***>
Subject: RE: [ROCm-Developer-Tools/roctracer] Memory Pool destructor uses allocator_default. (#54)

Hi Kiumars,
Do we have any activity on this issue??
https://github.com/ROCm-Developer-Tools/roctracer/issues/54

Many thanks,
TT.

**Comment by bertwesarg** [comment]
Fixed in 9d728f74a14cbce6aaa4fa8d74d6be1ab0cd9c84
