### ISSUE TITLE
roctracer + rocprof --hsa_trace does not work unless soft links are created manually

### ISSUE THREAD

**Issue by sanyalington** [ROCm/roctracer#6]
After installing roctracer, I expected rocprof --hsa-trace to work.
However, that failed with these errors:
Tool lib "/opt/rocm/rocprofiler/lib/libroctracer64.so" failed to load.
Tool lib "/opt/rocm/rocprofiler/tool/libtracer_tool.so" failed to load.

Creating these soft links made things work:
 ln -s /opt/rocm/roctracer/lib/libroctracer64.so /opt/rocm/rocprofiler/lib/libroctracer64.so
ln -s /opt/rocm/roctracer/tool/libtracer_tool.so /opt/rocm/rocprofiler/tool/libtracer_tool.so

**Comment by JMadgwick** [comment]
I can confirm this issue. Both `roctracer-dev` and `rcoprof-dev` are installed but links are not set up as part of the installation. Creating the links (as above) fixes the errors.

**Comment by eshcherb** [comment]
Will be fixed in the next ROCm release.
Will put the workaround in ROCm release documentation.

**Comment by eshcherb** [comment]
Fixed in ROCm 2.7
