### ISSUE TITLE
roctracer output for hipLaunchKernel does not include launch parameters

### ISSUE THREAD

**Issue by lfmeadow** [ROCm/roctracer#70]
e.g.:
```
rocprof --timestamp on --hip-trace -d profdata make run
...
in profdata/.../hip_api_trace.txt:

hipLaunchKernel(function_address=0x2011d8, numBlocks={}, dimBlocks={}, args=0x7ffde3d4d1d0, sharedMemBytes=0, stream=0)
```
The data for numBlocks etc is there for hipModuleLaunchKernel but not for hipLaunchKernel. It does show up in the rocprof counter output.

**Comment by lmoriche** [comment]
This should be fixed in ROCm-5.3:

hipLaunchKernel(function_address=0x200a50, numBlocks={z=1, y=1, x=2}, dimBlocks={z=1, y=1, x=128}, args=0x7ffc0ed19378, sharedMemBytes=1024, stream=0)
