### ISSUE TITLE
Looking for dynamic instrumentation tool for AMD GPU

### ISSUE THREAD

**Issue by William-An** [ROCm/roctracer#76]
Hello all,

I am currently working on a research project and wonder if rocm suite provides binary instrumentation for AMD GPUs, similar to the NVIDIA nvbit and Intel Pin tool. I have looked into the rocm profiler and tracer but they are all on API calls level tracing, while the project wants to use tracing in the ISA level.

**Comment by jamesxu2** [comment]
Hi @William-An , 

Sorry for the late response - The ROCm suite does provide rocprof-sys (formerly named Omnitrace) which can perform binary instrumentation. 

See: https://github.com/ROCm/omnitrace?tab=readme-ov-file#binary-instrumentation
and https://rocm.docs.amd.com/projects/omnitrace/en/latest/how-to/instrumenting-rewriting-binary-application.html
