### ISSUE TITLE
`stream__val` value for `hipStreamCreate*` gives invalid values

### ISSUE THREAD

**Issue by bertwesarg** [ROCm/roctracer#78]
The arguments for these callbacks include `.stream` and `.stream__val`. Based on `/opt/rocm-5.2.0/include/hip/hcc_detail/hip_prof_str.h`  `.stream__val` should be the value when dereferencing `.stream` in the EXIT phase. Though I get different values between `*.stream` and `.stream__val` for all `hipStreamCreate*` functions.

An example:

the callback sees the following values in the EXIT phase:

- `.stream = 0x7ffc6046c4a0`
- `*.stream = 0x2379830`
- `stream__val = 0x2375cb0`

The caller of `hipStreamCreate` sees this value: `0x2379830`

Can someone sched some light on the difference. Thanks.

**Comment by ppanchad-amd** [comment]
@bertwesarg Apologies for the lack of response.  Can you please check you still see this issue with the latest ROCm 6.2? If not, please close the ticket. Thanks!

**Comment by jamesxu2** [comment]
Hi @bertwesarg , I'm not sure how you're using these variables. When working with streams, you shouldn't need to use more than the hipStream_t handle. You can look at the most recent documentation on [HIP Stream Management](https://rocm.docs.amd.com/projects/HIP/en/latest/doxygen/html/group___stream.html) for more information.

Also, unfortunately I don't see any real references to the stream__val internally, so it's possible the API has changed by now, to the point where this variable is unused or not meant for external users to access.

If you do provide more information on what exactly you're trying to do with these variables, I might be able to help further.

**Comment by bertwesarg** [comment]
@all As roctracer will be replaced with rocprofiler SDK, I don't see a reason to continue here, do you?

**Comment by jamesxu2** [comment]
@bertwesarg , feel free to close this issue.
