### ISSUE TITLE
README Outdated: Include File

### ISSUE THREAD

**Issue by ax3l** [ROCm/roctracer#79]
This project's README is outdated with respect to the recommended include.

As of ROCm 5.2.0 on Crusher at least, I get the following warning when including `<roctx.h>`:
```
/opt/rocm-5.2.0/hip/../roctracer/include/roctx.h:26:9: warning: This file is deprecated. Use file from include path /opt/rocm-ver/include/ and prefix with roctracer [-W#pragma-messages]
#pragma message("This file is deprecated. Use file from include path /opt/rocm-ver/include/ and prefix with roctracer")
        ^
```

I assume the new include we should use is `roctracer/roctx.h`?

Likewise for `#include <roctracer_ext.h>` -> `#include <roctracer/roctracer_ext.h>`?

cc @arghdos

**Comment by skyreflectedinmirrors** [comment]
@frepaul -- is the new include path schema documented anywhere publicly?

**Comment by skyreflectedinmirrors** [comment]
@ax3l  -- I believe this is correct, but I am waiting on @frepaul who implemented this.

**Comment by frepaul** [comment]
@ax3l  @arghdos : #pragma message is valid and requesting applications to change accordingly.
Will work on updating the README as well, as we completely move away from the old method.
Public info here: https://docs.amd.com/bundle/ROCm-Release-Notes-v5.2/page/Deprecations_and_Warnings.html

**Comment by ppanchad-amd** [comment]
@ax3l Apologies for the lack of response.  Can you please check with the latest ROCm 6.2 to see if this issue still occurs?  If not, please close the ticket. Thanks!

**Comment by tcgu-amd** [comment]
@ax3l This should be fixed in commit https://github.com/ROCm/roctracer/commit/725d289a2b2ea551958cc3dc59d9ff59f7baf9f1. Closing the issue. Thanks!
