### ISSUE TITLE
Question: can rocTX work with rocprofv2 API?

### ISSUE THREAD

**Issue by tiandi111** [ROCm/roctracer#93]
I'm wondering if rocTX works with rocprofv2 API?

Thanks!

**Comment by jrmadsen** [comment]
It is supposed to but the rocprofiler v2 API found in ROCm 5.7 is undergoing a lot of changes in the next release. I would hold off on developing against the current rocprofiler v2 API until then

**Comment by tiandi111** [comment]
Thanks.

**Comment by tiandi111** [comment]
Thanks
